HOME_ENERGY_FILE_LOCATION = "custom_home_data.csv"
LOAD_COL_INDEX = 0
SOLAR_GENERATION_FILE_LOCATION = ""
ENERGY_COL_INDEX = 0
# Time in hours
NUM_TIME_STEP_BINS = 24
TIME_STEP = 1
PEAK_TIME_BEGIN = 5
PEAK_TIME_END = 9
# Cost in ____
PEAK_TIME_COST = 1
COST = 1
PEAK_TIME_SELL = 1
SELL = 1
# Battery limits
MAX_DISCHARGE = -10
MAX_CHARGE = 10
MAX_BATTERY_CAPACITY = 14000 #Wh
NUM_BATTERY_CAPACITY_BINS = 14
# TODO Max load parameters
# V Table
MIN_ACCEPTABLE_DELTA = .5