HOME_ENERGY_FILE_LOCATION = ""
LOAD_COL_INDEX = 0
SOLAR_GENERATION_FILE_LOCATION = ""
ENERGY_COL_INDEX = 0
# Time in seconds
TIME_STEP = 15
PEAK_TIME_BEGIN = 5
PEAK_TIME_END = 9
# Cost in ____
PEAK_TIME_COST = 1
COST = 1
PEAK_TIME_SELL = 1
SELL = 1
# TODO Max load parameters